name: Run tests on repository dispatch  # Nombre del flujo de trabajo

on:
  repository_dispatch:  # Configura el evento que desencadena este flujo de trabajo
    types: [run-tests]  # Este flujo de trabajo se activará cuando se envíe un evento 'repository_dispatch' con el tipo 'run-tests'

jobs:
  test:  # Define un trabajo llamado 'test'
    runs-on: ubuntu-latest  # Especifica que este trabajo se ejecutará en un entorno Ubuntu más reciente
    
    steps:  # Define los pasos a seguir en este trabajo
      - name: Checkout repository  # Paso para clonar el repositorio
        uses: actions/checkout@v2  # Usa la acción oficial de GitHub para clonar el repositorio

      # - name: Install dependencies  # Paso para instalar las dependencias
      #   run: npm install  # Ejecuta el comando 'npm install' para instalar las dependencias del proyecto

      - name: Run tests  # Paso para ejecutar las pruebas
        run: echo "jknjkjkn"  # Ejecuta el comando 'npm test' para ejecutar las pruebas del proyecto
