name: Repository Dispatch
on:
  repository_dispatch:
    types: [my-event]

jobs:
  myEvent:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: main  

      - name: Echo client payload values
        run: |
          echo "Event: ${{ github.event.client_payload.event }}"
          echo "Repository: ${{ github.event.client_payload.repo }}"
          echo "Ref: ${{ github.event.client_payload.ref }}"
          echo "Workflow: ${{ github.event.client_payload.workflow }}"
          echo "Author: ${{ github.event.client_payload.author }}"
          echo "Commit URL: ${{ github.event.client_payload.commit_url }}"
          echo "Commit Message: ${{ github.event.client_payload.commit_message }}"
          echo "Mensaje: ${{ github.event.client_payload.mensaje }}"
          echo "Color: ${{ github.event.client_payload.color }}"
          echo "Pipeline URL: ${{ github.event.client_payload.pipeline_url }}"  
          echo "Pull Request URL: ${{ github.event.client_payload.pull_request_url }}"

      - name: Send message to discord
        run: |
          event="${{ github.event.client_payload.event }}"
          repo="${{ github.event.client_payload.repo }}"
          ref="${{ github.event.client_payload.ref }}"
          workflow="${{ github.event.client_payload.workflow }}"
          author="${{ github.event.client_payload.author }}"
          commit_url="${{ github.event.client_payload.commit_url }}"
          commit_message="${{ github.event.client_payload.commit_message }}"
          mensaje="${{ github.event.client_payload.mensaje }}"
          color="${{ github.event.client_payload.color }}"
          solucion="Ninguna solución específica proporcionada"
          pipeline_url="${{ github.event.client_payload.pipeline_url }}" 
          pull_request_url="${{ github.event.client_payload.pull_request_url }}"
          message="{\"username\": \"GitHub Actions\", \"avatar_url\": \"https://github.com/github.png\", \"embeds\": [{\"title\": \"$mensaje\", \"color\": $color, \"fields\": [{\"name\": \"Pull Request\", \"value\": \"[Ir al pull request]($pull_request_url)\"}, {\"name\": \"Sugerencia\", \"value\": \"$solucion\"}, {\"name\": \"Detalles del Evento\", \"value\": \"Evento: $event\\nRepositorio: $repo\\nRef: $ref\\nFlujo de trabajo: $workflow\\nAutor: $author\\nMensaje del Commit: $commit_message\\n[Ver commit]($commit_url)\"}]}]}"

          curl -X POST -H 'Content-Type: application/json' -d "$message" https://discord.com/api/webhooks/1247924987877392495/EC0Ahcm-VSjZA21AfPAM0DrE2qha9iiCvClGEHjZNyk7U_abysiEPrbnhT4jaOtKqlMZ
