name: Run tests on repository dispatch

on:
  repository_dispatch:
    types: [run-tests]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          repository: Automation-Armada/PactumJS-TS-Cucucumber  # Repositorio que contiene package.json
          path: ./Devops  # Ruta relativa donde se clonará el repositorio

      - name: Install dependencies
        run: npm install --prefix ./Devops  # Instalar dependencias en el directorio clonado

      - name: Run tests
        run: npm test --prefix ./Devops  # Ejecutar pruebas en el directorio clonado
