name: Enviar mensaje a Discord
on:
  workflow_run:
    workflows: ["Ejemplo de GitHub Actions"]
    types:
      - completed

jobs:
  enviar-mensaje:
    runs-on: ubuntu-latest

    steps:
      - name: Obtener resultado del primer workflow
        id: obtener-resultado
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const mensaje = ${{ toJson(needs.build.outputs.mensaje) }};
            return mensaje;

      - name: Enviar mensaje a Discord
        if: always()
        run: |
          mensaje="${{ steps.obtener-resultado.outputs.resultado }}"
          color=65280  
          solucion="Ninguna solución específica proporcionada"
          repo_url="https://github.com/$GITHUB_REPOSITORY"
          pipeline_url="$repo_url/actions/runs/$GITHUB_RUN_ID"
          message="{\"username\": \"GitHub Actions\", \"avatar_url\": \"https://github.com/github.png\", \"embeds\": [{\"title\": \"Nuevo mensaje desde GitHub Actions\", \"color\": $color, \"fields\": [{\"name\": \"Pipeline\", \"value\": \"[Ir al pipeline]($pipeline_url)\"}, {\"name\": \"Sugerencia\", \"value\": \"$solucion\"}, {\"name\": \"Mensaje\", \"value\": \"$mensaje\"}]}]}"
          
          curl -X POST -H 'Content-Type: application/json' -d "$message" https://discord.com/api/webhooks/1243269132460363807/MNMmEyqEm8TAclOPDP3D5GJz388lybSwudkuKtcfAnRjIjxCNPeQOg3Cx48-i-P4lhXy
