name: PR Yml

on:
  pull_request:
    types: [opened]

jobs:
  pr:
    runs-on: ubuntu-latest
    steps:
      - name: Send message to discord
        env:
          DISCORD_WEBHOOK_URL: https://discord.com/api/webhooks/1262462826539126825/Wmf6s7_MLl_qinTIK7pcOThEigAi0ZUB85wDKHJVy_u1rjzkAscIocfr6Xu45_XZvWbJ
        run: |
          event="pull_request"
          repo="${{ github.repository }}"
          ref="${{ github.ref }}"
          workflow="${{ github.workflow }}"
          author="${{ github.actor }}"
          commit_url="${{ github.event.pull_request.html_url }}"
          commit_message="${{ github.event.pull_request.title }}"
          mensaje="New Pull Request Opened"
          color=7506394  # Example color in decimal
          pipeline_url="${{ github.server_url }}/${{ github.repository }}/actions"
          pull_request_url="${{ github.event.pull_request.html_url }}"

          message="{\"username\": \"GitHub Actions\", \"avatar_url\": \"https://github.com/github.png\", \"embeds\": [{\"title\": \"$mensaje\", \"color\": $color, \"fields\": [{\"name\": \"Pull Request\", \"value\": \"[go to pull request]($pull_request_url)\"}, {\"name\": \"Event Details\", \"value\": \"Event: $event\\nRepository: $repo\\nRef: $ref\\nWorkflow: $workflow\\nAuthor: $author\\nCommit Message: $commit_message\\n[See commit]($commit_url)\"}]}]}"

          curl -X POST -H 'Content-Type: application/json' -d "$message" $DISCORD_WEBHOOK_URL

# name: Repository Dispatch
# on:
#   repository_dispatch:
#     types: [my-event]

# jobs:
#   myEvent:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v3
#         with:
#           ref: main  

#       # - name: Echo client payload values
#       #   run: |
#       #     echo "Event: ${{ github.event.client_payload.event }}"
#       #     echo "Repository: ${{ github.event.client_payload.repo }}"
#       #     echo "Ref: ${{ github.event.client_payload.ref }}"
#       #     echo "Workflow: ${{ github.event.client_payload.workflow }}"
#       #     echo "Author: ${{ github.event.client_payload.author }}"
#       #     echo "Commit URL: ${{ github.event.client_payload.commit_url }}"
#       #     echo "Commit Message: ${{ github.event.client_payload.commit_message }}"
#       #     echo "Mensaje: ${{ github.event.client_payload.mensaje }}"
#       #     echo "Color: ${{ github.event.client_payload.color }}"
#       #     echo "Pipeline URL: ${{ github.event.client_payload.pipeline_url }}"  
#       #     echo "Pull Request URL: ${{ github.event.client_payload.pull_request_url }}"

