name: Repository Dispatch
on:
  repository_dispatch:
    types: [my-event]

jobs:
  myEvent:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: main  # Asegúrate de ajustar la rama según tus necesidades

      - name: Echo client payload values
        run: |
          echo "Event: ${{ github.event.client_payload.event }}"
          echo "Repository: ${{ github.event.client_payload.repo }}"
          echo "Ref: ${{ github.event.client_payload.ref }}"
          echo "Workflow: ${{ github.event.client_payload.workflow }}"
          echo "Author: ${{ github.event.client_payload.author }}"
          echo "Commit URL: ${{ github.event.client_payload.commit_url }}"
          echo "Commit Message: ${{ github.event.client_payload.commit_message }}"
          echo "Mensaje: ${{ github.event.client_payload.mensaje }}"
          echo "Color: ${{ github.event.client_payload.color }}"
          echo "Solucion: ${{ github.event.client_payload.solucion }}"
          echo "Repository URL: ${{ github.event.client_payload.repo_url }}"
          echo "Pipeline URL: ${{ github.event.client_payload.pipeline_url }}"
           curl -X POST -H 'Content-Type: application/json' -d "$message" https://discord.com/api/webhooks/1243269132460363807/MNMmEyqEm8TAclOPDP3D5GJz388lybSwudkuKtcfAnRjIjxCNPeQOg3Cx48-i-P4lhXy
